### PR TITLE
add chinese readme 

### PR DESCRIPTION
**Pull request by sungerk**
support for chinese tutorial，and i will continue to focus on the project

### CODE REVIEW

**Comment by VictorAlbertos** [comment]
Hi @sungerk 

This is cool :)

But I can't accept this pull request because you have removed the english comments from the source code, specifically from the class `Persistence`. Could you revert that specific commit, "Update Persistence.java"? And for future contributions on this translation support keep that on mind ;)

Thanks!

**Comment by sungerk** [comment]
I'm sorry, I did not consider this, and tomorrow I will update this file

**Comment by sungerk** [comment]
Unfortunately ,what the fuck of great firewall of china, now i can't connecting the world internet ，and can't download this project to the local，because of my shadowsocks agent can't be used.  I'll change it as soon as possible.

**Comment by VictorAlbertos** [comment]
Yeah, don't worry. Whenever you can ;)

**Pull request closed without merging**
