### PR TITLE
Support fetch data firstly from cache and then  from loader in one call

### PR DESCRIPTION
**Pull request by jiangecho**
In some scenario: I need to fetch data firstly from local cache and then from loader in one call.
But please know that: two test cases failed, and I still not figure out the root cause.

failed test cases:
```
io.rx_cache.internal.ProxyProvidersTest > When_No_Reply_Then_Get_Mock FAILED
    java.lang.IndexOutOfBoundsException at ProxyProvidersTest.java:87

io.rx_cache.internal.ProxyProvidersTest > When_No_Evict_Cache_Then_Source_Retrieved_Is_Not_Cloud FAILED
    java.lang.IndexOutOfBoundsException at ProxyProvidersTest.java:80

80 tests completed, 2 failed
```

### CODE REVIEW

**Comment by hick209** [comment]
I like the idea @jiangecho.

Another good scenario to use this approach is when **useExpiredData** is set and the data is indeed expired. So you would present that (the expired) to the user up until the new data comes from the loader.

What do you think of picking which requests should use the CacheThenLoader approach (using an annotation for example)? Otherwise every time you load something from the cache, it will also make a network request, even in cases where you know for sure the data haven't changed.

**Comment by jiangecho** [comment]
@hick209 Thanks.
Yeah, I agree. Not all requests need the CacheThenLoader approach, CacheThenLoader should only work for specified request, not all requests.
As you mentioned, annotation maybe a good choice to implement CacheThenLoader approach, and I will try.

**Comment by jiangecho** [comment]
I update the PR.
Add ```CacheThenLoader``` and ```ForceLoader``` annotation.
```CacheThenLoader```: the request will firstly load data from cache, then go on to load data from loader.
```ForceLoader```: the request will ignore the cache, and directly load data from loader.

**Comment by VictorAlbertos** [comment]
Hi!

@jiangecho what do you need this feature for, exactly?

Reviewing your pull request I can see two main changes, `ForceLoader` and `CacheThenLoader`. 

About `ForceLoader`, I think this functionality does not make sense. Because if you always want to get the data from its original source, why would you use RxCache in the first place? Instead you just would call directly your observable from your repository layer without using RxCache. 

About `CacheThenLoader`, I can not see the point of this functionality either. If you dispatch the data already cached just to show something to the user meanwhile the desired data is been retrieving from the loader observable, I think the user experience could get a little messy. Your data could change suddenly the UI while the user were playing with it (a RecyclerView being suddenly refreshened without any user interaction). But most importantly, **RxCache it’s just a cache, it can not accumulate features to be a little more handy for some edge cases**. And as you already notice, you can always use the `concat` operator in your repository layer to achieve this behaviour.  

And any change should be commited in a new branch, and every change needs to be cover by proper tests.  
 
It’s my fault because I’ve not added a contributing.md file which explains what kind of features could be desirable to implement and how to do it. I’ll fix that. 

Anyway, thanks @jiangecho for your contribution. And I’m sorry because I can not integrate these changes to RxCache library. But feel free to expose your arguments in more detail, please.

**Comment by jiangecho** [comment]
@VictorAlbertos Thank you for your explanation.
About ```CacheThenLoader```, I think in a news app or something else like Tweet, I need this feature.
For example, in a news app, when I start the app, I want to see  the cached news page immediately, not a blank page. The page would show a loading indicator, and after the fresh news is loaded, update the news page.
And about the ```ForceLoader```, I mean that when user force to fresh, just use it. But maybe it is not a good solution.

**Comment by VictorAlbertos** [comment]
Hi @jiangecho :)

For the case when the user request to update some data, you need to configure your endpoint to accept an instance of `Evict` class or some of its subclasses (depending of the evicting scope you required for that particular case). The solution that you suggested can not operate at runtime -it’s an annotation which sticks to the method  signature, I mean this provider would be evicting always the data -not when the user requires it.

About CacheThenLoader issue, if you check how Twitter updates its cached data you won’t see that approach. Twitter app updates their cached data on the background -using some kind of push notification mechanism (gcm?, I dunno), not when the app is opening. And this is very important. You should not updating the cached data when users open the application, instead the cached data should be updated periodically using push notifications. 

For that matter, I created [RxGcm](https://github.com/VictorAlbertos/RxGcm), a reactive wrapper around google cloud messaging (aka gcm). But I advice you to wait until monday to check it, because I’m going to change the api in order to set a more strongly defined architectural approach.

**Comment by jiangecho** [comment]
@VictorAlbertos Yeah, I agree with you.
Oh, I am from China, behind the GFW, the great wall in 21st century, we can access Twitter and use GCM.
Ok, please focus on the following app(汽车之家, an app about auto), when I start the app, it will firstly display the cached data, and then loading fresh data. If the fresh data is available, the page will be refreshed and the fresh data is inserted, otherwise, show an error toast, and the page continue to show the cached data. Any suggestion about implementing such feature with out GCM.
Thank you~
cache then loader

**Pull request closed without merging**
