### PR TITLE
Add the README_ZH.

### PR DESCRIPTION
**Pull request by qingmei2**

### CODE REVIEW

**Comment by JessYanCoding** [comment]
😃

**Comment by qingmei2** [comment]
@VictorAlbertos 
Hi , VictorAlbertos
I try to spend some time translating your articles into Chinese, maybe It can help some developers to quickly understand this library 🙂

**Comment by qingmei2** [comment]
@JessYanCoding 
Thanks for your suggestion 🤝   :-D

**Comment by VictorAlbertos** [comment]
Thanks @qingmei2 :) Can you please squash your commits before merging this PR?

**Comment by qingmei2** [comment]
@VictorAlbertos 
My fault，I resubmit the PR  :)  #110

**Pull request closed without merging**
