### PR TITLE
Added @ProviderKey annotation to fix issues with Proguard.

### LINKED ISSUE #96: Bug: method name used used as provider-key is very error prone.
# Problem

We use Proguard to obfuscate our code, last week we had a major issue in a production version of our app. After investigating we found an issue that was caused by Proguard, which converted two methods with different names to two methods with equal names (which is exactly what Proguard should do).

**Before Proguard:**

```
interface Cache {
    Observable<List<ObjectA>> listObjectA(Observable<List<ObjectA>> observable, DynamicKey dynamicKey, EvictProvider evictProvider);

    Observable<List<ObjectB>> listObjectB(Observable<List<ObjectB>> observable, DynamicKey dynamicKey, EvictProvider evictProvider);

}
```

**After Proguard** (simplified for the sake of the example):

```
interface Cache {
    Observable<List<ObjectA>> a(Observable<List<ObjectA>> observable, DynamicKey dynamicKey, EvictProvider evictProvider);

    Observable<List<ObjectB>> a(Observable<List<ObjectB>> observable, DynamicKey dynamicKey, EvictProvider evictProvider);

}
```

After Proguard the method names are the same: `a` (this is totally valid Java code!). This is a problem as RxCache currently uses the method name as provider key. This leads to ugly run-time `ClassCastExceptions` because two providers use the same provider-key (and thus use the same "space" in Memory).

# Dirty solution

To prevent this we can either keep the `Cache` class using the following Proguard rule:

```
-keep class org.example.Cache { *; }
```

# Proposed solution

But it would be way nicer if we can manually provide the provider key using an Annotation, as we don't use Proguard for nothing (we want the names to be non-readable). This also enables us to change the method names without writing a migration.

**Example:**
```
interface Cache {

    @ProviderKey("some-key-for-list-a")
    Observable<List<ObjectA>> listObjectA(Observable<List<ObjectA>> observable, DynamicKey dynamicKey, EvictProvider evictProvider);

   @ProviderKey("some-key-for-list-b")
    Observable<List<ObjectB>> listObjectB(Observable<List<ObjectB>> observable, DynamicKey dynamicKey, EvictProvider evictProvider);

}
```

# Impact

Modifying the  `ProxyTranslator.getProviderKey()` should be very simple and straightforward, it also wont impact other components of RxCache like migration.

# Remarks

- If for some good reason this change is rejected at least make sure the Proguard section of the documentation is complete and includes a warning!
- Another way to fix this is to use the full method signature (not only the name but also the argument types and return types etc.) But this will probably break migration and some other components and is thus not fit for the job.

Let me know what you think, I'm willing to create a pull-request for the proposed changes!

### PR DESCRIPTION
**Pull request by Rolf-Smit**
Added `@ProviderKey` annotation that can be used to supply the provider-key. This fixes #96.

**Changes in this PR:**
 - Added `@ProviderKey` annotation including a very simple test case to test whether the annotation is detected and used;
- Updated README. Proguard section to warn Proguard users about problems that are very likely to occur when not using this annotation.
- Updated README, Usage section to inform users about the annotation and when it should/can be used.

Please let me know what you think of it.

### CODE REVIEW

**Comment by Rolf-Smit** [comment]
@VictorAlbertos it looks like the build server build failed to to a exception in a test case, however locally this test works fine. So you might want to look into this.

Another thing to note here is that some test cases failed out-of-the-box (current master branch) without any changes applied.

**The following test cases fail on the current master branch on my machine:**

- `ProvidersRxCacheEvictExpirableRecordsTest.When_Expirable_Records_Evict` (expected 4, was 7)
   This one is probably caused because the `evict` method fails to delete the file on Windows because it's in use (delete returns false):

```
  @Override public void evict(String key) {
    key = safetyKey(key);
    final File file = new File(cacheDirectory, key);
    file.delete();
  }
```

I've investigated the issue and it seems that the `MoshSpeaker` (which the tests use) does not close the cache file after reading it, if created an issue for this here: https://github.com/VictorAlbertos/Jolyglot/issues/7

After changing the `MoshSpeaker` to `GsonSpeaker` this test does not fail anymore.


- `ProvidersRxCacheEvictExpiredRecordsTest._2_Perform_Evicting_Task_And_Check_Results` (expected 0, was 50)
This test does not fail when using the `GsonSpeaker`.

- `ProvidersRxCacheEvictExpiredRecordsTest._3_Populate_Disk_With_No_Expired_Records` (expected 0, was 9)
This test does not fail when using the `GsonSpeaker`.

- `ProvidersRxCacheEvictExpiredRecordsTest._5_Populate_Disk_With_Expired_Encrypted_Records` (expected 0, was 24)
This test does not fail when using the `GsonSpeaker`.

- `ProvidersRxCacheEvictExpiredRecordsTest._6_Perform_Evicting_Task_And_Check_Results` (expected 0, was 24)
This test does not fail when using the `GsonSpeaker`.

- `ProvidersRxCacheTest._14_When_0_Is_The_Value_For_Life_Time_Not_Cached_Ad_Infinitum` 

This test **fails** when using the `GsonSpeaker`, with the `MoshiSpeaker` it does not fail. This is weird as the speaker implementation should not affect anything. This needs a look.

- `ProvidersRxCacheTest._15_When_Evict_All_Evict_All` (expected 100, was 106)
- `RxCacheBuilderValidationTest.Cache_Directory_Not_Writable` (unexpected exception: `java.lang.IllegalStateException: Cannot modify permissions`

**Comment by VictorAlbertos** [comment]
I cloned your repo and run test locally and everyone of them just passes. I'll investigate the issue. 

In order to accept the PR, please move the annotation `@ProviderKey` from `core` module to `runtime` module. `core`has no knowledge whatsoever about `runtime` api, actually, `core` is the same lib which ReactiveCache uses internally. And please, remove [this comment](https://github.com/Rolf-Smit/RxCache/blob/95dea87d5c6d1e6c506c37cec06fd593e35ad204/runtime/src/main/java/io/rx_cache2/internal/ProxyTranslator.java#L64) too ;)

Thanks!

**Comment by Rolf-Smit** [comment]
@VictorAlbertos done!

**Comment by VictorAlbertos** [comment]
Thanks @Rolf-Smit ;)

New version available: `compile "com.github.VictorAlbertos.RxCache:runtime:1.8.1-2.x"`

**Pull request merged**
